spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
# ë°˜ë“œì‹œ mysql -u root -p 1234ë¡œ ì ‘ì†í›„ create database mydatabaseë¥¼ ë§Œë“¤ê³ ë‚˜ì„œ í• ê²ƒ.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        jdbc.time_zone: Asia/Seoul
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      
  security:
    jwt:
      secret: your-super-secret-key-that-is-at-least-64-bytes-long-for-hs512-to-work-correctly
      expiration: 86400000 # 24 hours
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: workmates.verify@gmail.com
    password: bwis vylc bbkh gxez
    properties:
      mail:
        smtp:
          debug: true
          auth: true
          starttls:
            enable: true
            required: true
          timeout: 5000
          connectiontimeout: 5000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.product.backend: debug
     # ğŸ‘‡ WebSocket ë””ë²„ê¹…ìš© ë¡œê·¸ ë ˆë²¨ ì¶”ê°€
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

open-ai-api:
  chat:
    url: https://api.openai.com/v1/chat/completions
    model: gpt-4o

  image-generate:
    url: https://api.openai.com/v1/images/generations
    model: dall-e-3 

