spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
# ë°˜ë“œì‹œ mysql -u root -p 1234ë¡œ ì ‘ì†í›„ create database mydatabaseë¥¼ ë§Œë“¤ê³ ë‚˜ì„œ í• ê²ƒ.
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    show-sql: true

  security:
    jwt:
      secret: your-super-secret-key-that-is-at-least-64-bytes-long-for-hs512-to-work-correctly
      expiration: 86400000 # 24 hours

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.product.backend: debug
     # ğŸ‘‡ WebSocket ë””ë²„ê¹…ìš© ë¡œê·¸ ë ˆë²¨ ì¶”ê°€
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

google-translate-api:
  path: C:\Users\soldesk\Desktop\api_resource\grounded-vision-467403-f8-24b49089c814.json
  google-project-id: grounded-vision-467403-f8
  location: global